<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="index.aspx.cs" Inherits="grid3.index" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>

</head>
<body>
    <div class="container">
    <form id="form1" novalidate="" runat="server">
    <div>
        <asp:GridView ID="GridView1" CssClass="table table-bordered" runat="server" DataKeyNames="id" AutoGenerateColumns="false" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" OnRowDeleting="GridView1_RowDeleting" OnSelectedIndexChanged="GridView1_SelectedIndexChanged"> 
            <Columns>
                <asp:BoundField DataField="id" Visible="false"  />
                <asp:BoundField DataField="Name" HeaderText="Name" />
                <asp:BoundField DataField="LastName" HeaderText="LastName"/>
            </Columns>
        </asp:GridView>
    </div>
      <hr />
        <div class="form-group col-md-6">
                    <label class="form-control-label" for="inputSuccess2">Enter Name</label>                   
                    <asp:TextBox ID="Name" class="form-control" runat="server"  required=""></asp:TextBox>
                    <div class="valid-feedback">Nice! You got this one!</div>
                    <div class="invalid-feedback">Sorry, you missed this one.</div>
         </div>
        <div class="form-group col-md-6">
                    <label class="form-control-label" for="inputSuccess2">Enter LastName</label>                   
                    <asp:TextBox ID="LastName" class="form-control" runat="server"  required=""></asp:TextBox>
                    <div class="valid-feedback">Nice! You got this one!</div>
                    <div class="invalid-feedback">Sorry, you missed this one.</div>
         </div>
        <div class="form-group col-md-6">
        <asp:Button ID="Button1" runat="server" CssClass="btn btn-primary" Text="Submit" OnClick="Button1_Click" />            
         </div>
        <div class="form-group col-md-6">
        <asp:Button ID="Button2" CssClass="btn btn-primary" runat="server" Text="Update"  Visible="false" OnClick="Button2_Click"/>
         </div>
        <div class="form-group col-md-6">
        <asp:Button ID="Button3" runat="server" CssClass="btn btn-primary" OnClick="Button3_Click" Text="Reset" />
         </div>
        
        
         
    
        
              
    </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#Button1").click(function (event) {

                // Fetch form to apply custom Bootstrap validation
                var form = $("#form1")

                if (form[0].checkValidity() === false) {
                    event.preventDefault()
                    event.stopPropagation()
                }

                form.addClass('was-validated');
                // Perform ajax submit here...

            });
        });
 </script>
</body>
</html>
